### ISSUE TITLE
Package cannot find the executable file.

### ISSUE THREAD

**Issue by PaulJ505** [ViChyavIn/atom-tic80#4]
Greetings. I have a small problem with atom-tic80. I installed it and when I tried to create a project, it told me that it wasn't able to find TIC-80's executable file. I remembered then, that I didn't put TIC-80.exe in default location, so I went to package settings to set my new location, which is C:\Tic-80. After that I tried to create a project again and it didn't work again. Atom-tic80 is still telling me that it can't find the TIC-80's executable file even when I typed the correct path. 

I tried to type this path in different ways. Here's a short list:
C:\Tic-80
c:\tic-80
C:\Tic-80\tic80.exe

None of them worked obviously.

**Comment by NikitaIvanovV** [comment]
@PaulJ505 Hello! Executable path is an absolute path to the executable, like `C:\Tic-80\tic80.exe`. Are you sure you got the correct path to your TIC-80 executable file? If yes, try doubling dashes in your input (for example, instead of typing `C:\Tic-80\tic80.exe` type `C:\\Tic-80\\tic80.exe`).

**Comment by PaulJ505** [comment]
Okay. I tried to type C:\Tic-80\tic80.exe once again and it worked this time, which is weird, but that message about the package not being able to find executable file is not showing anymore. But I can't run my code in TIC-80. I saved my code as "test.lua" and tried to run it, but nothing happened. I probably didn't understood your instructions, but tbh. I don't need the ability, to run my code through Atom that much. I mostly wanted a software where I could get a code being colorized in a TIC-80 way and with autocompletion, which your package is giving me so I am able to code on a much bigger space than what TIC-80 is giving. I will just copy what I typed straight into TIC-80's code editor.

**Comment by NikitaIvanovV** [comment]
Weird. Glad to know it works now!

After I learned about this issue, I tried using the package with the latest TIC-80 0.90 and I couldn't run a cart file. And now you say you couldn't either, so it's not a problem on my end! Thank you for opening the issue, now I'm aware of another problem and will try to fix it.
