### ISSUE TITLE
Can't run tic with the latest version (0.90)

### ISSUE THREAD

**Issue by NikitaIvanovV** [ViChyavIn/atom-tic80#5]
Invoking Run and Run File commands does not start TIC-80. Probably has something to do with the new cli features in the version 0.90.

**Comment by NikitaIvanovV** [comment]
@PaulJ505 In [this discussion](https://github.com/ViChyavIn/atom-tic80/issues/4#issuecomment-884048615) you said you encountered this problem. May I ask you which version of TIC-80 do you use?

**Comment by PaulJ505** [comment]
@ViChyavIn I am using version 0.90.1706.
